# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "puppetlabs/ubuntu-12.04-64-nocm"
        config.vm.network :private_network, ip: "192.168.33.52"
        config.vm.hostname = "ubuntu-1204.vagrant.local"
        config.vm.provider :virtualbox do |vb|
        	vb.memory = 1024
                vb.name = "ubuntu-1204"
        end
end
